[workspace]
members = [
    "del-msh-pyo3",
    "del-msh-core",
    "del-msh-nalgebra",
    "del-msh-cudarc",
    "del-msh-candle"
]
exclude = [
    "del-msh-cudarc-kernel"
]
resolver = "2"

[workspace.package]
version = "0.1.39"
edition = "2021"
authors = ["Nobuyuki Umetani <n.umetani@gmail.com>"]
license = "MIT"
repository = "https://github.com/nobuyuki83/del-msh/"
description = "mesh utility library for computer graphics research and prototyping"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.86"
rand = "0.9.0"
rand_chacha = "0.9.0"
ordered-float = "4.2.1"
num-traits = "0.2.19"
nalgebra = "0.33.0"
arrayref = "0.3.9"
slice-of-array = "0.3.2"
pyo3 = { version = "0.23.4", features = ["extension-module"] }
numpy = "0.23.0"

# internal
del-msh-nalgebra = { path="del-msh-nalgebra"}
del-msh-core = {path="del-msh-core"}
del-msh-cudarc = {path="del-msh-cudarc"}
del-msh-cudarc-kernel = {path="del-msh-cudarc-kernel"}

# for development
# del-geo-core = { path="../del-geo/del-geo-core"}
# del-geo-nalgebra = { path="../del-geo/del-geo-nalgebra"}
# candle-core = { git="https://github.com/huggingface/candle.git" }

# for GitHub push
del-geo-core = { git = "https://github.com/nobuyuki83/del-geo.git"}
del-geo-nalgebra = { git = "https://github.com/nobuyuki83/del-geo.git"}
candle-core = { git="https://github.com/huggingface/candle.git" }

# for deploy
# del-geo-core = "=0.1.33"
# del-geo-nalgebra = "=0.1.33"
# del-cudarc = "=0.1.2"
# candle-core = "=0.8.2"

