[package]
name = "del-msh-candle"
description = "hgoehoge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
cuda = ["candle-core/cuda", "del-msh-cudarc/cuda"]

[dependencies]
rand.workspace = true
anyhow.workspace = true
nalgebra.workspace = true
serde_json = "1.0.133"
candle-core = { git = "https://github.com/huggingface/candle.git"}
del-geo-nalgebra.workspace = true
del-msh-core.workspace = true
del-msh-nalgebra.workspace = true
del-msh-cudarc = { workspace = true, optional = true }
# del-candle = {path="../../del-candle"}

[dev-dependencies]
